### ISSUE TITLE
not parsing correctly https://curl.trillworks.com/

### ISSUE THREAD

**Issue by GgAaYyAaNn** [NickCarneiro/curlconverter#245] opened 2020-11-14 21:21 UTC
```
curl 'https://www.dealabs.com/graphql' \
  -H 'authority: www.dealabs.com' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'x-request-type: application/vnd.pepper.v1+json' \
  -H 'x-xsrf-token: "XoPgRlWQGF3r4qc5KC9znBJ8JI1ArzQYOQK0Z1z0"' \
  -H 'x-requested-with: XMLHttpRequest' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'origin: https://www.dealabs.com' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://www.dealabs.com/discussions/le-topic-des-erreurs-de-prix-1056379' \
  -H 'accept-language: si,en;q=0.9,en-US;q=0.8' \
  -H 'cookie: __cfduid=d98b8f5827acffe51f7828f3955e8489f1604764610; f_v=%22d8c6cd00-2111-11eb-bd21-0242ac110002%22; _ga=GA1.2.225802619.1604764618; pepper_session=%2283d0b1d1939b95c47a2f3a6c6ee7466eea153468%22; u_l=0; xsrf_t=%22XoPgRlWQGF3r4qc5KC9znBJ8JI1ArzQYOQK0Z1z0%22; _gid=GA1.2.850596604.1605383567; _gat=1' \
  --data-binary $'[{"query":"query topComments($threadId: IDFilter\u0021, $order: SortFilter) {  topComments: comments(filter: {threadId: $threadId, order: $order, top: {is: true}}) {    items {      ...commentFields    }  }}        fragment commentFields on Comment {  commentId  threadId  url  preparedHtmlContent  user {    ...userMediumAvatarFields    ...userNameFields    ...userPersonaFields    bestBadge {      ...badgeFields    }  }  likes  deletable  liked  reported  reportable  source  status  createdAt  updatedAt  ignored  popular  deletedBy {    username  }  notes {    content    createdAt    user {      username    }  }  lastEdit {    reason    timeAgo    userId  }}        fragment userMediumAvatarFields on User {  userId  isDeletedOrPendingDeletion  imageUrls(slot: \\"default\\", variations: [\\"user_small_avatar\\"])}        fragment userNameFields on User {  userId  username  isUserProfileHidden  isDeletedOrPendingDeletion}        fragment userPersonaFields on User {  persona {    type    text  }}        fragment badgeFields on Badge {  badgeId  level {    ...badgeLevelFields  }}        fragment badgeLevelFields on BadgeLevel {  key  name  description}","variables":{"threadId":{"eq":"1056379"}}},{"query":"query comments($filter: CommentFilter\u0021, $limit: Int, $page: Int) {  comments(filter: $filter, limit: $limit, page: $page) {    items {      ...commentFields    }    pagination {      ...paginationFields    }  }}        fragment commentFields on Comment {  commentId  threadId  url  preparedHtmlContent  user {    ...userMediumAvatarFields    ...userNameFields    ...userPersonaFields    bestBadge {      ...badgeFields    }  }  likes  deletable  liked  reported  reportable  source  status  createdAt  updatedAt  ignored  popular  deletedBy {    username  }  notes {    content    createdAt    user {      username    }  }  lastEdit {    reason    timeAgo    userId  }}        fragment userMediumAvatarFields on User {  userId  isDeletedOrPendingDeletion  imageUrls(slot: \\"default\\", variations: [\\"user_small_avatar\\"])}        fragment userNameFields on User {  userId  username  isUserProfileHidden  isDeletedOrPendingDeletion}        fragment userPersonaFields on User {  persona {    type    text  }}        fragment badgeFields on Badge {  badgeId  level {    ...badgeLevelFields  }}        fragment badgeLevelFields on BadgeLevel {  key  name  description}        fragment paginationFields on Pagination {  count  current  last  next  previous  size  order}","variables":{"filter":{"threadId":{"eq":"1056379"},"order":null},"page":1}},{"query":"query commentSettings($scope: ID\u0021, $comments: Boolean = false, $form: Boolean = false, $adminTools: Boolean = false) {  features {    commentForm(scope: $scope) {      ...commentFeatures @include(if: $comments)      ...commentFormFeatures @include(if: $form)    }    adminTools(scope: \\"comment\\") @include(if: $adminTools) {      ...commentAdminFeatures    }  }  settings {    application {      appStore @include(if: $comments)      reCaptcha2Key: reCaptcha(version: 1) @include(if: $form)    }  }}        fragment commentFeatures on CommentFormFeatures {  permalink  issueReporting}        fragment commentFormFeatures on CommentFormFeatures {  enabled  subscribe  reCaptcha  wysiwyg {    html    expand  }}        fragment commentAdminFeatures on AdminToolFeatures {  deletable  demoteComment  directMessage  editable  enabled  expanded  imposeInfractions  inspectUser  moderate  promoteComment  showCountry  spamReport}","variables":{"scope":"1056379","comments":true,"form":true,"adminTools":true}},{"query":"query newComments($scope: ID\u0021, $limit: Int) {  newComments(threadId: $scope, limit: $limit) {    page    count    latest  }}","variables":{"scope":"1056379"}},{"query":"query currentUserAvatar($variations: [String\u0021]\u0021) {  me {    userId    imageUrls(slot: \\"default\\", variations: $variations)  }}","variables":{"variations":["user_small_avatar"]}}]' \
  --compressed

```
parsed is

```
import requests

headers = {
    'authority': 'www.dealabs.com',
    'accept': 'application/json, text/plain, */*',
    'x-request-type': 'application/vnd.pepper.v1+json',
    'x-xsrf-token': '"XoPgRlWQGF3r4qc5KC9znBJ8JI1ArzQYOQK0Z1z0"',
    'x-requested-with': 'XMLHttpRequest',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36',
    'content-type': 'application/json',
    'origin': 'https://www.dealabs.com',
    'sec-fetch-site': 'same-origin',
    'sec-fetch-mode': 'cors',
    'sec-fetch-dest': 'empty',
    'referer': 'https://www.dealabs.com/discussions/le-topic-des-erreurs-de-prix-1056379',
    'accept-language': 'si,en;q=0.9,en-US;q=0.8',
    'cookie': '__cfduid=d98b8f5827acffe51f7828f3955e8489f1604764610; f_v=%22d8c6cd00-2111-11eb-bd21-0242ac110002%22; _ga=GA1.2.225802619.1604764618; pepper_session=%2283d0b1d1939b95c47a2f3a6c6ee7466eea153468%22; u_l=0; xsrf_t=%22XoPgRlWQGF3r4qc5KC9znBJ8JI1ArzQYOQK0Z1z0%22; _gid=GA1.2.850596604.1605383567; _gat=1',
}

data = '$[{"query":"query topComments($threadId: IDFilter\\u0021, $order: SortFilter) { topComments: comments(filter: {threadId: $threadId, order: $order, top: {is: true}}) { items { ...commentFields } }} fragment commentFields on Comment { commentId threadId url preparedHtmlContent user { ...userMediumAvatarFields ...userNameFields ...userPersonaFields bestBadge { ...badgeFields } } likes deletable liked reported reportable source status createdAt updatedAt ignored popular deletedBy { username } notes { content createdAt user { username } } lastEdit { reason timeAgo userId }} fragment userMediumAvatarFields on User { userId isDeletedOrPendingDeletion imageUrls(slot: \\\\"default\\\\", variations: [\\\\"user_small_avatar\\\\"])} fragment userNameFields on User { userId username isUserProfileHidden isDeletedOrPendingDeletion} fragment userPersonaFields on User { persona { type text }} fragment badgeFields on Badge { badgeId level { ...badgeLevelFields }} fragment badgeLevelFields on BadgeLevel { key name description}","variables":{"threadId":{"eq":"1056379"}}},{"query":"query comments($filter: CommentFilter\\u0021, $limit: Int, $page: Int) { comments(filter: $filter, limit: $limit, page: $page) { items { ...commentFields } pagination { ...paginationFields } }} fragment commentFields on Comment { commentId threadId url preparedHtmlContent user { ...userMediumAvatarFields ...userNameFields ...userPersonaFields bestBadge { ...badgeFields } } likes deletable liked reported reportable source status createdAt updatedAt ignored popular deletedBy { username } notes { content createdAt user { username } } lastEdit { reason timeAgo userId }} fragment userMediumAvatarFields on User { userId isDeletedOrPendingDeletion imageUrls(slot: \\\\"default\\\\", variations: [\\\\"user_small_avatar\\\\"])} fragment userNameFields on User { userId username isUserProfileHidden isDeletedOrPendingDeletion} fragment userPersonaFields on User { persona { type text }} fragment badgeFields on Badge { badgeId level { ...badgeLevelFields }} fragment badgeLevelFields on BadgeLevel { key name description} fragment paginationFields on Pagination { count current last next previous size order}","variables":{"filter":{"threadId":{"eq":"1056379"},"order":null},"page":1}},{"query":"query commentSettings($scope: ID\\u0021, $comments: Boolean = false, $form: Boolean = false, $adminTools: Boolean = false) { features { commentForm(scope: $scope) { ...commentFeatures @include(if: $comments) ...commentFormFeatures @include(if: $form) } adminTools(scope: \\\\"comment\\\\") @include(if: $adminTools) { ...commentAdminFeatures } } settings { application { appStore @include(if: $comments) reCaptcha2Key: reCaptcha(version: 1) @include(if: $form) } }} fragment commentFeatures on CommentFormFeatures { permalink issueReporting} fragment commentFormFeatures on CommentFormFeatures { enabled subscribe reCaptcha wysiwyg { html expand }} fragment commentAdminFeatures on AdminToolFeatures { deletable demoteComment directMessage editable enabled expanded imposeInfractions inspectUser moderate promoteComment showCountry spamReport}","variables":{"scope":"1056379","comments":true,"form":true,"adminTools":true}},{"query":"query newComments($scope: ID\\u0021, $limit: Int) { newComments(threadId: $scope, limit: $limit) { page count latest }}","variables":{"scope":"1056379"}},{"query":"query currentUserAvatar($variations: [String\\u0021]\\u0021) { me { userId imageUrls(slot: \\\\"default\\\\", variations: $variations) }}","variables":{"variations":["user_small_avatar"]}}]'

response = requests.post('https://www.dealabs.com/graphql', headers=headers, data=data)
```
but data is not correct
it works if parsed data is
`[{"query":"query topComments($threadId: IDFilter\u0021, $order: SortFilter) {  topComments: comments(filter: {threadId: $threadId, order: $order, top: {is: true}}) {    items {      ...commentFields    }  }}        fragment commentFields on Comment {  commentId  threadId  url  preparedHtmlContent  user {    ...userMediumAvatarFields    ...userNameFields    ...userPersonaFields    bestBadge {      ...badgeFields    }  }  likes  deletable  liked  reported  reportable  source  status  createdAt  updatedAt  ignored  popular  deletedBy {    username  }  notes {    content    createdAt    user {      username    }  }  lastEdit {    reason    timeAgo    userId  }}        fragment userMediumAvatarFields on User {  userId  isDeletedOrPendingDeletion  imageUrls(slot: \\"default\\", variations: [\\"user_small_avatar\\"])}        fragment userNameFields on User {  userId  username  isUserProfileHidden  isDeletedOrPendingDeletion}        fragment userPersonaFields on User {  persona {    type    text  }}        fragment badgeFields on Badge {  badgeId  level {    ...badgeLevelFields  }}        fragment badgeLevelFields on BadgeLevel {  key  name  description}","variables":{"threadId":{"eq":"1056379"}}},{"query":"query comments($filter: CommentFilter\u0021, $limit: Int, $page: Int) {  comments(filter: $filter, limit: $limit, page: $page) {    items {      ...commentFields    }    pagination {      ...paginationFields    }  }}        fragment commentFields on Comment {  commentId  threadId  url  preparedHtmlContent  user {    ...userMediumAvatarFields    ...userNameFields    ...userPersonaFields    bestBadge {      ...badgeFields    }  }  likes  deletable  liked  reported  reportable  source  status  createdAt  updatedAt  ignored  popular  deletedBy {    username  }  notes {    content    createdAt    user {      username    }  }  lastEdit {    reason    timeAgo    userId  }}        fragment userMediumAvatarFields on User {  userId  isDeletedOrPendingDeletion  imageUrls(slot: \\"default\\", variations: [\\"user_small_avatar\\"])}        fragment userNameFields on User {  userId  username  isUserProfileHidden  isDeletedOrPendingDeletion}        fragment userPersonaFields on User {  persona {    type    text  }}        fragment badgeFields on Badge {  badgeId  level {    ...badgeLevelFields  }}        fragment badgeLevelFields on BadgeLevel {  key  name  description}        fragment paginationFields on Pagination {  count  current  last  next  previous  size  order}","variables":{"filter":{"threadId":{"eq":"1056379"},"order":null},"page":1}},{"query":"query commentSettings($scope: ID\u0021, $comments: Boolean = false, $form: Boolean = false, $adminTools: Boolean = false) {  features {    commentForm(scope: $scope) {      ...commentFeatures @include(if: $comments)      ...commentFormFeatures @include(if: $form)    }    adminTools(scope: \\"comment\\") @include(if: $adminTools) {      ...commentAdminFeatures    }  }  settings {    application {      appStore @include(if: $comments)      reCaptcha2Key: reCaptcha(version: 1) @include(if: $form)    }  }}        fragment commentFeatures on CommentFormFeatures {  permalink  issueReporting}        fragment commentFormFeatures on CommentFormFeatures {  enabled  subscribe  reCaptcha  wysiwyg {    html    expand  }}        fragment commentAdminFeatures on AdminToolFeatures {  deletable  demoteComment  directMessage  editable  enabled  expanded  imposeInfractions  inspectUser  moderate  promoteComment  showCountry  spamReport}","variables":{"scope":"1056379","comments":true,"form":true,"adminTools":true}},{"query":"query newComments($scope: ID\u0021, $limit: Int) {  newComments(threadId: $scope, limit: $limit) {    page    count    latest  }}","variables":{"scope":"1056379"}},{"query":"query currentUserAvatar($variations: [String\u0021]\u0021) {  me {    userId    imageUrls(slot: \\"default\\", variations: $variations)  }}","variables":{"variations":["user_small_avatar"]}}]`

**Comment by verhovsky** [comment] 2021-10-03 08:36
dupe of #207 

And if you try it on https://curl.trillworks.com/ , it works now.

**Closed by verhovsky** 2021-10-03 08:36 UTC
Labels: duplicate
